'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DevCake.WoW.SPP2Launcher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apache() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apache", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Friend ReadOnly Property cmangos_classic() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cmangos_classic", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmangos_classic_core() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmangos_classic_core", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Friend ReadOnly Property cmangos_orange() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cmangos_orange", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Friend ReadOnly Property cmangos_realmd_started() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cmangos_realmd_started", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Friend ReadOnly Property cmangos_red() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cmangos_red", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Friend ReadOnly Property cmangos_tbc() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cmangos_tbc", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmangos_tbc_core() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmangos_tbc_core", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Friend ReadOnly Property cmangos_wotlk() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cmangos_wotlk", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmangos_wotlk_core() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmangos_wotlk_core", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Каталог {0} не найден!.
        '''</summary>
        Friend ReadOnly Property E001_DirNotFound() As String
            Get
                Return ResourceManager.GetString("E001_DirNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Single Player Project v2 уже запущен!.
        '''</summary>
        Friend ReadOnly Property E002_AlreadyRunning() As String
            Get
                Return ResourceManager.GetString("E002_AlreadyRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Ошибка!.
        '''</summary>
        Friend ReadOnly Property E003_ErrorCaption() As String
            Get
                Return ResourceManager.GetString("E003_ErrorCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Не найдено ни одного модуля сервера WoW!.
        '''</summary>
        Friend ReadOnly Property E004_ModulesNotFound() As String
            Get
                Return ResourceManager.GetString("E004_ModulesNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Не найден каталог расположения сервера MySQL!.
        '''</summary>
        Friend ReadOnly Property E005_MySqlNotFound() As String
            Get
                Return ResourceManager.GetString("E005_MySqlNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Не найден каталог расположения сервера Apache!.
        '''</summary>
        Friend ReadOnly Property E006_ApacheNotFound() As String
            Get
                Return ResourceManager.GetString("E006_ApacheNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Не найдены исполняемые файлы CMaNGOS.
        '''</summary>
        Friend ReadOnly Property E007_MangoNotFound() As String
            Get
                Return ResourceManager.GetString("E007_MangoNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Неизвестный модуль расширения {0}.
        '''</summary>
        Friend ReadOnly Property E008_UnknownModule() As String
            Get
                Return ResourceManager.GetString("E008_UnknownModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на MySQL выдал исключение:.
        '''</summary>
        Friend ReadOnly Property E009_MySqlException() As String
            Get
                Return ResourceManager.GetString("E009_MySqlException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Ошибка загрузки основной конфигурации!.
        '''</summary>
        Friend ReadOnly Property E011_ErrorMainConfig() As String
            Get
                Return ResourceManager.GetString("E011_ErrorMainConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Realmd выдал исключение:.
        '''</summary>
        Friend ReadOnly Property E012_RealmdException() As String
            Get
                Return ResourceManager.GetString("E012_RealmdException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Не найден каталог Settings модулей серверов..
        '''</summary>
        Friend ReadOnly Property E013_SettingsNotFound() As String
            Get
                Return ResourceManager.GetString("E013_SettingsNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на World выдал исключение:.
        '''</summary>
        Friend ReadOnly Property E014_WorldException() As String
            Get
                Return ResourceManager.GetString("E014_WorldException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Сервер REALMD внезапно прекратил работу {0} раз. {1}.
        '''</summary>
        Friend ReadOnly Property E015_RealmdCrashed() As String
            Get
                Return ResourceManager.GetString("E015_RealmdCrashed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Сервер WORLD внезапно прекратил работу {0} раз. {1}.
        '''</summary>
        Friend ReadOnly Property E016_WorldCrashed() As String
            Get
                Return ResourceManager.GetString("E016_WorldCrashed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Произошла ошибка. Подробности в Log-файле приложения..
        '''</summary>
        Friend ReadOnly Property E017_SeeLog() As String
            Get
                Return ResourceManager.GetString("E017_SeeLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Исключение при запуске сервера {0}.
        '''</summary>
        Friend ReadOnly Property E018_StartException() As String
            Get
                Return ResourceManager.GetString("E018_StartException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Исключение при остановке сервера {0}.
        '''</summary>
        Friend ReadOnly Property E019_StopException() As String
            Get
                Return ResourceManager.GetString("E019_StopException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property green_ball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_ball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lan_switcher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lan_switcher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property locale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("locale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mysql() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mysql", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend ReadOnly Property notomono_regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("notomono_regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Инициализация базовых настроек приложения выполнена..
        '''</summary>
        Friend ReadOnly Property P001_BaseInit() As String
            Get
                Return ResourceManager.GetString("P001_BaseInit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Добавлен серверный модуль {0}.
        '''</summary>
        Friend ReadOnly Property P002_ModuleAdded() As String
            Get
                Return ResourceManager.GetString("P002_ModuleAdded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Файлы exe (*.exe)|*.exe|Все файлы (*.*)|*.*.
        '''</summary>
        Friend ReadOnly Property P003_SetWowClientPath() As String
            Get
                Return ResourceManager.GetString("P003_SetWowClientPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Выберите сервер.
        '''</summary>
        Friend ReadOnly Property P004_SelectServer() As String
            Get
                Return ResourceManager.GetString("P004_SelectServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Выход из приложения..
        '''</summary>
        Friend ReadOnly Property P005_Exiting() As String
            Get
                Return ResourceManager.GetString("P005_Exiting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Для смены типа сервера требуется перезагрузка лаунчера. Выполнить сейчас?.
        '''</summary>
        Friend ReadOnly Property P006_NeedReboot() As String
            Get
                Return ResourceManager.GetString("P006_NeedReboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Сообщение.
        '''</summary>
        Friend ReadOnly Property P007_MessageCaption() As String
            Get
                Return ResourceManager.GetString("P007_MessageCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на установлен.
        '''</summary>
        Friend ReadOnly Property P008_Installed() As String
            Get
                Return ResourceManager.GetString("P008_Installed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на не установлен.
        '''</summary>
        Friend ReadOnly Property P009_NotInstalled() As String
            Get
                Return ResourceManager.GetString("P009_NotInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Single Player Project v2.
        '''</summary>
        Friend ReadOnly Property P010_LauncherCaption() As String
            Get
                Return ResourceManager.GetString("P010_LauncherCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Всего {0} чаров..
        '''</summary>
        Friend ReadOnly Property P011_AllChars() As String
            Get
                Return ResourceManager.GetString("P011_AllChars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Консольная команда: {0}.
        '''</summary>
        Friend ReadOnly Property P012_ConsoleCommand() As String
            Get
                Return ResourceManager.GetString("P012_ConsoleCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Включить сайт.
        '''</summary>
        Friend ReadOnly Property P013_SiteAutostart() As String
            Get
                Return ResourceManager.GetString("P013_SiteAutostart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Данное действие вызовет сброс настроек приложения по умолчанию. Продолжить?.
        '''</summary>
        Friend ReadOnly Property P014_Reset() As String
            Get
                Return ResourceManager.GetString("P014_Reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Изменение интерфейса на {0}. Произойдёт после перезагрузки..
        '''</summary>
        Friend ReadOnly Property P015_ChangeLocale() As String
            Get
                Return ResourceManager.GetString("P015_ChangeLocale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Внимание!.
        '''</summary>
        Friend ReadOnly Property P016_WarningCaption() As String
            Get
                Return ResourceManager.GetString("P016_WarningCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Создать.
        '''</summary>
        Friend ReadOnly Property P017_Create() As String
            Get
                Return ResourceManager.GetString("P017_Create", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Изменить.
        '''</summary>
        Friend ReadOnly Property P018_Change() As String
            Get
                Return ResourceManager.GetString("P018_Change", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Контроль над сервером включен..
        '''</summary>
        Friend ReadOnly Property P019_ControlEnabled() As String
            Get
                Return ResourceManager.GetString("P019_ControlEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Остановка сервера по требованию..
        '''</summary>
        Friend ReadOnly Property P020_NeedServerStop() As String
            Get
                Return ResourceManager.GetString("P020_NeedServerStop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Установлен таймер для {0} = {1}.
        '''</summary>
        Friend ReadOnly Property P021_TimerSetted() As String
            Get
                Return ResourceManager.GetString("P021_TimerSetted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Резервное копирование базы {0}.
        '''</summary>
        Friend ReadOnly Property P022_BackupStart() As String
            Get
                Return ResourceManager.GetString("P022_BackupStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Информация.
        '''</summary>
        Friend ReadOnly Property P023_InfoCaption() As String
            Get
                Return ResourceManager.GetString("P023_InfoCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Успешное завершение резервного копирования {0}.
        '''</summary>
        Friend ReadOnly Property P024_BackupSuccess() As String
            Get
                Return ResourceManager.GetString("P024_BackupSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Повторная загрузка лаунчера после селектора сервера..
        '''</summary>
        Friend ReadOnly Property P025_ReShowLauncher() As String
            Get
                Return ResourceManager.GetString("P025_ReShowLauncher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Применены настройки сервера {0}.
        '''</summary>
        Friend ReadOnly Property P026_SettingsApplied() As String
            Get
                Return ResourceManager.GetString("P026_SettingsApplied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Выбран сервер: {0}.
        '''</summary>
        Friend ReadOnly Property P027_ServerSelected() As String
            Get
                Return ResourceManager.GetString("P027_ServerSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Перезагрузка приложения..
        '''</summary>
        Friend ReadOnly Property P028_ApplicationRestart() As String
            Get
                Return ResourceManager.GetString("P028_ApplicationRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Запуск основного приложения..
        '''</summary>
        Friend ReadOnly Property P029_LaunchMain() As String
            Get
                Return ResourceManager.GetString("P029_LaunchMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Контроль над сервером отключен..
        '''</summary>
        Friend ReadOnly Property P030_ControlDisabled() As String
            Get
                Return ResourceManager.GetString("P030_ControlDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Изменения произойдут после перезагрузки приложения..
        '''</summary>
        Friend ReadOnly Property P031_ChangeToRestart() As String
            Get
                Return ResourceManager.GetString("P031_ChangeToRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Автосохранение БД....
        '''</summary>
        Friend ReadOnly Property P032_AutoBackup() As String
            Get
                Return ResourceManager.GetString("P032_AutoBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Сработал таймер {0}.
        '''</summary>
        Friend ReadOnly Property P033_TimerTriggered() As String
            Get
                Return ResourceManager.GetString("P033_TimerTriggered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Имя пользователя должно быть не менее четырёх символов..
        '''</summary>
        Friend ReadOnly Property P034_SmallLengthUserName() As String
            Get
                Return ResourceManager.GetString("P034_SmallLengthUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Пока есть проблемы для запуска сервера World. Отложено на 2 сек....
        '''</summary>
        Friend ReadOnly Property P035_ThereIsProblems() As String
            Get
                Return ResourceManager.GetString("P035_ThereIsProblems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Пароль пользователя должен быть не менее шести символов..
        '''</summary>
        Friend ReadOnly Property P036_SmallLengthUserPass() As String
            Get
                Return ResourceManager.GetString("P036_SmallLengthUserPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Сервер World не готов принимать команды....
        '''</summary>
        Friend ReadOnly Property P037_WorldNotStarted() As String
            Get
                Return ResourceManager.GetString("P037_WorldNotStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Аккаунт {0} не найден!.
        '''</summary>
        Friend ReadOnly Property P038_AccountNotFound() As String
            Get
                Return ResourceManager.GetString("P038_AccountNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Дождитесь окончания....
        '''</summary>
        Friend ReadOnly Property P039_WaitEnd() As String
            Get
                Return ResourceManager.GetString("P039_WaitEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Остановка неизолированных серверов..
        '''</summary>
        Friend ReadOnly Property P040_CommandShutdown() As String
            Get
                Return ResourceManager.GetString("P040_CommandShutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Сервер {0} уже запущен..
        '''</summary>
        Friend ReadOnly Property P041_AlreadyStarted() As String
            Get
                Return ResourceManager.GetString("P041_AlreadyStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Запуск сервера {0}.
        '''</summary>
        Friend ReadOnly Property P042_ServerStart() As String
            Get
                Return ResourceManager.GetString("P042_ServerStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Сервер {0} успешно запущен..
        '''</summary>
        Friend ReadOnly Property P043_ServerStarted() As String
            Get
                Return ResourceManager.GetString("P043_ServerStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Остановка сервера {0}.
        '''</summary>
        Friend ReadOnly Property P044_ServerStop() As String
            Get
                Return ResourceManager.GetString("P044_ServerStop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Сервер {0} успешно остановлен..
        '''</summary>
        Friend ReadOnly Property P045_ServerStopped() As String
            Get
                Return ResourceManager.GetString("P045_ServerStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Обнаружен процесс {0} которого не должно быть. Сервер изолирован до снятия проблемы..
        '''</summary>
        Friend ReadOnly Property P046_ProcessDetected() As String
            Get
                Return ResourceManager.GetString("P046_ProcessDetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Это самая незначительная проблема. Откройте меню Apache и выберите пункт меню &quot;Остановить&quot;..
        '''</summary>
        Friend ReadOnly Property P047_Locked01() As String
            Get
                Return ResourceManager.GetString("P047_Locked01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на В результате этих действий сервер разблокируется и станет доступным для подключения..
        '''</summary>
        Friend ReadOnly Property P047_Locked02() As String
            Get
                Return ResourceManager.GetString("P047_Locked02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Данный сервер следует останавливать самым последним и понимать возможные последствия!.
        '''</summary>
        Friend ReadOnly Property P047_Locked03() As String
            Get
                Return ResourceManager.GetString("P047_Locked03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Иначе - откройте меню MySQL, выберите пункт &quot;Остановить&quot; и дождитесь завершения процесса..
        '''</summary>
        Friend ReadOnly Property P047_Locked04() As String
            Get
                Return ResourceManager.GetString("P047_Locked04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Это самая серьёзная проблема! Непредусмотренная остановка сервера mangosd.exe всегда приводит к потере данных..
        '''</summary>
        Friend ReadOnly Property P047_Locked05() As String
            Get
                Return ResourceManager.GetString("P047_Locked05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Если есть возможность - зайдите в игру и наберите в консоли .saveall  и дождитесь завершения сохранения..
        '''</summary>
        Friend ReadOnly Property P047_Locked06() As String
            Get
                Return ResourceManager.GetString("P047_Locked06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Как вариант - зайдите в меню &quot;Сохранения&quot; и создайте резервную копию текущей базы данных..
        '''</summary>
        Friend ReadOnly Property P047_Locked07() As String
            Get
                Return ResourceManager.GetString("P047_Locked07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Что произойдёт: Возможно придётся заново войти на сайт связанный с данным сервером..
        '''</summary>
        Friend ReadOnly Property P047_Locked08() As String
            Get
                Return ResourceManager.GetString("P047_Locked08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на В данном случае идеальным будет создать резервную копию базы данных..
        '''</summary>
        Friend ReadOnly Property P047_Locked09() As String
            Get
                Return ResourceManager.GetString("P047_Locked09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Что произойдёт если я выберу &quot;Остановить&quot;: Скорее всего вы потеряете несохранённые данные..
        '''</summary>
        Friend ReadOnly Property P047_Locked10() As String
            Get
                Return ResourceManager.GetString("P047_Locked10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Что произойдёт, если я завершу процесс через диспетчер задач: То же, и в предыдущем случае..
        '''</summary>
        Friend ReadOnly Property P047_Locked11() As String
            Get
                Return ResourceManager.GetString("P047_Locked11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на А если нажму &quot;РАЗБЛОКИРОВАТЬ ВСЁ&quot;: Всё то же самое, что написано выше, зато быстро..
        '''</summary>
        Friend ReadOnly Property P047_Locked12() As String
            Get
                Return ResourceManager.GetString("P047_Locked12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Что же делать? - Не всё возможно сделать по щелчку пальцев, некоторые вещи требуют ручного вмешательства..
        '''</summary>
        Friend ReadOnly Property P047_Locked13() As String
            Get
                Return ResourceManager.GetString("P047_Locked13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Backup {0}....
        '''</summary>
        Friend ReadOnly Property P048_Backup() As String
            Get
                Return ResourceManager.GetString("P048_Backup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Не удалось запустить сервер {0}.
        '''</summary>
        Friend ReadOnly Property P049_NotStarted() As String
            Get
                Return ResourceManager.GetString("P049_NotStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Данное действие вызовет остановку всех запущенных серверов. Продолжить?.
        '''</summary>
        Friend ReadOnly Property P050_Exit1() As String
            Get
                Return ResourceManager.GetString("P050_Exit1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Данное действие закроет приложение, однако все изолированные сервера продолжат работу. Выполнить выход?.
        '''</summary>
        Friend ReadOnly Property P050_Exit2() As String
            Get
                Return ResourceManager.GetString("P050_Exit2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Сервер {0} невозможно запустить без доступного сервера MySQL..
        '''</summary>
        Friend ReadOnly Property P051_NeedMySQL() As String
            Get
                Return ResourceManager.GetString("P051_NeedMySQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на  - ЭТО ПЕРВЫЙ ЗАПУСК!.
        '''</summary>
        Friend ReadOnly Property P052_FirstStart() As String
            Get
                Return ResourceManager.GetString("P052_FirstStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Выполнить резерное копирование (autosave) прямо сейчас?.
        '''</summary>
        Friend ReadOnly Property P053_CreateBackup() As String
            Get
                Return ResourceManager.GetString("P053_CreateBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Для выполнения необходимо подключение к MySQL!.
        '''</summary>
        Friend ReadOnly Property P054_NeedMySQL() As String
            Get
                Return ResourceManager.GetString("P054_NeedMySQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Перезапуск через 10 сек..
        '''</summary>
        Friend ReadOnly Property P055_RestartIs() As String
            Get
                Return ResourceManager.GetString("P055_RestartIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Пользователь с именем {0} уже существует!.
        '''</summary>
        Friend ReadOnly Property P056_UserFound() As String
            Get
                Return ResourceManager.GetString("P056_UserFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Повторить?.
        '''</summary>
        Friend ReadOnly Property P057_Repeat() As String
            Get
                Return ResourceManager.GetString("P057_Repeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Параметры аккаунта успешно изменены!.
        '''</summary>
        Friend ReadOnly Property P058_AccountChanged() As String
            Get
                Return ResourceManager.GetString("P058_AccountChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property protect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("protect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property red_ball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_ball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property server() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property server_restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property server_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property server_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tbc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tbc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vanilla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vanilla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wotlk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wotlk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Friend ReadOnly Property wow() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("wow", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
