'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Функция автоматического сохранения My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        '''<summary>
        '''Язык интерфейса
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Язык интерфейса"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("en-GB")>  _
        Public Property Locale() As String
            Get
                Return CType(Me("Locale"),String)
            End Get
            Set
                Me("Locale") = value
            End Set
        End Property
        
        '''<summary>
        '''Путь к файлу запуска клиента WoW
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Путь к файлу запуска клиента WoW"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property WowClientPath() As String
            Get
                Return CType(Me("WowClientPath"),String)
            End Get
            Set
                Me("WowClientPath") = value
            End Set
        End Property
        
        '''<summary>
        '''Предыдущий запущенный сервер
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Предыдущий запущенный сервер"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastLoadedServerType() As String
            Get
                Return CType(Me("LastLoadedServerType"),String)
            End Get
            Set
                Me("LastLoadedServerType") = value
            End Set
        End Property
        
        '''<summary>
        '''Автоматический запуск Apache
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Автоматический запуск Apache"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ApacheAutostart() As Boolean
            Get
                Return CType(Me("ApacheAutostart"),Boolean)
            End Get
            Set
                Me("ApacheAutostart") = value
            End Set
        End Property
        
        '''<summary>
        '''Автоматический запуск MySQL
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Автоматический запуск MySQL"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MySqlAutostart() As Boolean
            Get
                Return CType(Me("MySqlAutostart"),Boolean)
            End Get
            Set
                Me("MySqlAutostart") = value
            End Set
        End Property
        
        '''<summary>
        '''Использовать встроенный Apache
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Использовать встроенный Apache"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseIntApache() As Boolean
            Get
                Return CType(Me("UseIntApache"),Boolean)
            End Get
            Set
                Me("UseIntApache") = value
            End Set
        End Property
        
        '''<summary>
        '''Использовать встроенный MySQL
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Использовать встроенный MySQL"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseIntMySQL() As Boolean
            Get
                Return CType(Me("UseIntMySQL"),Boolean)
            End Get
            Set
                Me("UseIntMySQL") = value
            End Set
        End Property
        
        '''<summary>
        '''Автоматический запуск сервера TBC
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Автоматический запуск сервера TBC"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ServerTbcAutostart() As Boolean
            Get
                Return CType(Me("ServerTbcAutostart"),Boolean)
            End Get
            Set
                Me("ServerTbcAutostart") = value
            End Set
        End Property
        
        '''<summary>
        '''Автоматический запуск сервера WotLK
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Автоматический запуск сервера WotLK"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ServerWotlkAutostart() As Boolean
            Get
                Return CType(Me("ServerWotlkAutostart"),Boolean)
            End Get
            Set
                Me("ServerWotlkAutostart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>  _
        Public Property MySqlWotlkIntHost() As String
            Get
                Return CType(Me("MySqlWotlkIntHost"),String)
            End Get
            Set
                Me("MySqlWotlkIntHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3310")>  _
        Public Property MySqlWotlkIntPort() As String
            Get
                Return CType(Me("MySqlWotlkIntPort"),String)
            End Get
            Set
                Me("MySqlWotlkIntPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property MySqlWotlkIntUserName() As String
            Get
                Return CType(Me("MySqlWotlkIntUserName"),String)
            End Get
            Set
                Me("MySqlWotlkIntUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("123456")>  _
        Public Property MySqlWotlkIntPassword() As String
            Get
                Return CType(Me("MySqlWotlkIntPassword"),String)
            End Get
            Set
                Me("MySqlWotlkIntPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wotlkarmory")>  _
        Public Property MySqlWotlkIntArmory() As String
            Get
                Return CType(Me("MySqlWotlkIntArmory"),String)
            End Get
            Set
                Me("MySqlWotlkIntArmory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wotlkchracters")>  _
        Public Property MySqlWotlkIntCharacters() As String
            Get
                Return CType(Me("MySqlWotlkIntCharacters"),String)
            End Get
            Set
                Me("MySqlWotlkIntCharacters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wotlklogs")>  _
        Public Property MySqlWotlkIntLogs() As String
            Get
                Return CType(Me("MySqlWotlkIntLogs"),String)
            End Get
            Set
                Me("MySqlWotlkIntLogs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wotlkmangos")>  _
        Public Property MySqlWotlkIntMangos() As String
            Get
                Return CType(Me("MySqlWotlkIntMangos"),String)
            End Get
            Set
                Me("MySqlWotlkIntMangos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wotlkplayerbots")>  _
        Public Property MySqlWotlkIntPlayerbots() As String
            Get
                Return CType(Me("MySqlWotlkIntPlayerbots"),String)
            End Get
            Set
                Me("MySqlWotlkIntPlayerbots") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wotlkrealmd")>  _
        Public Property MySqlWotlkIntRealmd() As String
            Get
                Return CType(Me("MySqlWotlkIntRealmd"),String)
            End Get
            Set
                Me("MySqlWotlkIntRealmd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlWotlkExtHost() As String
            Get
                Return CType(Me("MySqlWotlkExtHost"),String)
            End Get
            Set
                Me("MySqlWotlkExtHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlWotlkExtPort() As String
            Get
                Return CType(Me("MySqlWotlkExtPort"),String)
            End Get
            Set
                Me("MySqlWotlkExtPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlWotlkExtUserName() As String
            Get
                Return CType(Me("MySqlWotlkExtUserName"),String)
            End Get
            Set
                Me("MySqlWotlkExtUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlWotlkExtPassword() As String
            Get
                Return CType(Me("MySqlWotlkExtPassword"),String)
            End Get
            Set
                Me("MySqlWotlkExtPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlWotlkExtArmory() As String
            Get
                Return CType(Me("MySqlWotlkExtArmory"),String)
            End Get
            Set
                Me("MySqlWotlkExtArmory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlWotlkExtCharacters() As String
            Get
                Return CType(Me("MySqlWotlkExtCharacters"),String)
            End Get
            Set
                Me("MySqlWotlkExtCharacters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlWotlkExtLogs() As String
            Get
                Return CType(Me("MySqlWotlkExtLogs"),String)
            End Get
            Set
                Me("MySqlWotlkExtLogs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlWotlkExtMangos() As String
            Get
                Return CType(Me("MySqlWotlkExtMangos"),String)
            End Get
            Set
                Me("MySqlWotlkExtMangos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlWotlkExtPlayerbots() As String
            Get
                Return CType(Me("MySqlWotlkExtPlayerbots"),String)
            End Get
            Set
                Me("MySqlWotlkExtPlayerbots") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlWotlkExtRealmd() As String
            Get
                Return CType(Me("MySqlWotlkExtRealmd"),String)
            End Get
            Set
                Me("MySqlWotlkExtRealmd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>  _
        Public Property MySqlClassicIntHost() As String
            Get
                Return CType(Me("MySqlClassicIntHost"),String)
            End Get
            Set
                Me("MySqlClassicIntHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3310")>  _
        Public Property MySqlClassicIntPort() As String
            Get
                Return CType(Me("MySqlClassicIntPort"),String)
            End Get
            Set
                Me("MySqlClassicIntPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property MySqlClassicIntUserName() As String
            Get
                Return CType(Me("MySqlClassicIntUserName"),String)
            End Get
            Set
                Me("MySqlClassicIntUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("123456")>  _
        Public Property MySqlClassicIntPassword() As String
            Get
                Return CType(Me("MySqlClassicIntPassword"),String)
            End Get
            Set
                Me("MySqlClassicIntPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("classicarmory")>  _
        Public Property MySqlClassicIntArmory() As String
            Get
                Return CType(Me("MySqlClassicIntArmory"),String)
            End Get
            Set
                Me("MySqlClassicIntArmory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("classiccharacters")>  _
        Public Property MySqlClassicIntCharacters() As String
            Get
                Return CType(Me("MySqlClassicIntCharacters"),String)
            End Get
            Set
                Me("MySqlClassicIntCharacters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("classiclogs")>  _
        Public Property MySqlClassicIntLogs() As String
            Get
                Return CType(Me("MySqlClassicIntLogs"),String)
            End Get
            Set
                Me("MySqlClassicIntLogs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("classicmangos")>  _
        Public Property MySqlClassicIntMangos() As String
            Get
                Return CType(Me("MySqlClassicIntMangos"),String)
            End Get
            Set
                Me("MySqlClassicIntMangos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("classicplayerbots")>  _
        Public Property MySqlClassicIntPlayerbots() As String
            Get
                Return CType(Me("MySqlClassicIntPlayerbots"),String)
            End Get
            Set
                Me("MySqlClassicIntPlayerbots") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("classicrealmd")>  _
        Public Property MySqlClassicIntRealmd() As String
            Get
                Return CType(Me("MySqlClassicIntRealmd"),String)
            End Get
            Set
                Me("MySqlClassicIntRealmd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlClassicExtHost() As String
            Get
                Return CType(Me("MySqlClassicExtHost"),String)
            End Get
            Set
                Me("MySqlClassicExtHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlClassicExtPort() As String
            Get
                Return CType(Me("MySqlClassicExtPort"),String)
            End Get
            Set
                Me("MySqlClassicExtPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlClassicExtUserName() As String
            Get
                Return CType(Me("MySqlClassicExtUserName"),String)
            End Get
            Set
                Me("MySqlClassicExtUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlClassicExtPassword() As String
            Get
                Return CType(Me("MySqlClassicExtPassword"),String)
            End Get
            Set
                Me("MySqlClassicExtPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlClassicExtArmory() As String
            Get
                Return CType(Me("MySqlClassicExtArmory"),String)
            End Get
            Set
                Me("MySqlClassicExtArmory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlClassicExtCharacters() As String
            Get
                Return CType(Me("MySqlClassicExtCharacters"),String)
            End Get
            Set
                Me("MySqlClassicExtCharacters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlClassicExtLogs() As String
            Get
                Return CType(Me("MySqlClassicExtLogs"),String)
            End Get
            Set
                Me("MySqlClassicExtLogs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlClassicExtMangos() As String
            Get
                Return CType(Me("MySqlClassicExtMangos"),String)
            End Get
            Set
                Me("MySqlClassicExtMangos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlClassicExtPlayerbots() As String
            Get
                Return CType(Me("MySqlClassicExtPlayerbots"),String)
            End Get
            Set
                Me("MySqlClassicExtPlayerbots") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlClassicExtRealmd() As String
            Get
                Return CType(Me("MySqlClassicExtRealmd"),String)
            End Get
            Set
                Me("MySqlClassicExtRealmd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>  _
        Public Property MySqlTbcIntHost() As String
            Get
                Return CType(Me("MySqlTbcIntHost"),String)
            End Get
            Set
                Me("MySqlTbcIntHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3310")>  _
        Public Property MySqlTbcIntPort() As String
            Get
                Return CType(Me("MySqlTbcIntPort"),String)
            End Get
            Set
                Me("MySqlTbcIntPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property MySqlTbcIntUserName() As String
            Get
                Return CType(Me("MySqlTbcIntUserName"),String)
            End Get
            Set
                Me("MySqlTbcIntUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("123456")>  _
        Public Property MySqlTbcIntPassword() As String
            Get
                Return CType(Me("MySqlTbcIntPassword"),String)
            End Get
            Set
                Me("MySqlTbcIntPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tbcarmory")>  _
        Public Property MySqlTbcIntArmory() As String
            Get
                Return CType(Me("MySqlTbcIntArmory"),String)
            End Get
            Set
                Me("MySqlTbcIntArmory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tbccharacters")>  _
        Public Property MySqlTbcIntCharacters() As String
            Get
                Return CType(Me("MySqlTbcIntCharacters"),String)
            End Get
            Set
                Me("MySqlTbcIntCharacters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tbclogs")>  _
        Public Property MySqlTbcIntLogs() As String
            Get
                Return CType(Me("MySqlTbcIntLogs"),String)
            End Get
            Set
                Me("MySqlTbcIntLogs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tbcmangos")>  _
        Public Property MySqlTbcIntMangos() As String
            Get
                Return CType(Me("MySqlTbcIntMangos"),String)
            End Get
            Set
                Me("MySqlTbcIntMangos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tbcplayerbots")>  _
        Public Property MySqlTbcIntPlayerbots() As String
            Get
                Return CType(Me("MySqlTbcIntPlayerbots"),String)
            End Get
            Set
                Me("MySqlTbcIntPlayerbots") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tbcrealmd")>  _
        Public Property MySqlTbcIntRealmd() As String
            Get
                Return CType(Me("MySqlTbcIntRealmd"),String)
            End Get
            Set
                Me("MySqlTbcIntRealmd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlTbcExtHost() As String
            Get
                Return CType(Me("MySqlTbcExtHost"),String)
            End Get
            Set
                Me("MySqlTbcExtHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlTbcExtPort() As String
            Get
                Return CType(Me("MySqlTbcExtPort"),String)
            End Get
            Set
                Me("MySqlTbcExtPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlTbcExtUserName() As String
            Get
                Return CType(Me("MySqlTbcExtUserName"),String)
            End Get
            Set
                Me("MySqlTbcExtUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlTbcExtPassword() As String
            Get
                Return CType(Me("MySqlTbcExtPassword"),String)
            End Get
            Set
                Me("MySqlTbcExtPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlTbcExtArmory() As String
            Get
                Return CType(Me("MySqlTbcExtArmory"),String)
            End Get
            Set
                Me("MySqlTbcExtArmory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlTbcExtCharacters() As String
            Get
                Return CType(Me("MySqlTbcExtCharacters"),String)
            End Get
            Set
                Me("MySqlTbcExtCharacters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlTbcExtLogs() As String
            Get
                Return CType(Me("MySqlTbcExtLogs"),String)
            End Get
            Set
                Me("MySqlTbcExtLogs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlTbcExtMangos() As String
            Get
                Return CType(Me("MySqlTbcExtMangos"),String)
            End Get
            Set
                Me("MySqlTbcExtMangos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlTbcExtPlayerbots() As String
            Get
                Return CType(Me("MySqlTbcExtPlayerbots"),String)
            End Get
            Set
                Me("MySqlTbcExtPlayerbots") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlTbcExtRealmd() As String
            Get
                Return CType(Me("MySqlTbcExtRealmd"),String)
            End Get
            Set
                Me("MySqlTbcExtRealmd") = value
            End Set
        End Property
        
        '''<summary>
        '''Каталог проекта Single Player Project v2
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Каталог проекта Single Player Project v2"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\GAME\SERVER\WOW\SPP_Classics_V2")>  _
        Public Property DirSPP2() As String
            Get
                Return CType(Me("DirSPP2"),String)
            End Get
            Set
                Me("DirSPP2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ServerClassicAutostart() As Boolean
            Get
                Return CType(Me("ServerClassicAutostart"),Boolean)
            End Get
            Set
                Me("ServerClassicAutostart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ANY")>  _
        Public Property ApacheClassicIntHost() As String
            Get
                Return CType(Me("ApacheClassicIntHost"),String)
            End Get
            Set
                Me("ApacheClassicIntHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property ApacheClassicIntPort() As String
            Get
                Return CType(Me("ApacheClassicIntPort"),String)
            End Get
            Set
                Me("ApacheClassicIntPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ANY")>  _
        Public Property ApacheTbcIntHost() As String
            Get
                Return CType(Me("ApacheTbcIntHost"),String)
            End Get
            Set
                Me("ApacheTbcIntHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property ApacheTbcIntPort() As String
            Get
                Return CType(Me("ApacheTbcIntPort"),String)
            End Get
            Set
                Me("ApacheTbcIntPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ANY")>  _
        Public Property ApacheWotlkIntHost() As String
            Get
                Return CType(Me("ApacheWotlkIntHost"),String)
            End Get
            Set
                Me("ApacheWotlkIntHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property ApacheWotlkIntPort() As String
            Get
                Return CType(Me("ApacheWotlkIntPort"),String)
            End Get
            Set
                Me("ApacheWotlkIntPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ApacheClassicExtHost() As String
            Get
                Return CType(Me("ApacheClassicExtHost"),String)
            End Get
            Set
                Me("ApacheClassicExtHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ApacheClassicExtPort() As String
            Get
                Return CType(Me("ApacheClassicExtPort"),String)
            End Get
            Set
                Me("ApacheClassicExtPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ApacheTbcExtHost() As String
            Get
                Return CType(Me("ApacheTbcExtHost"),String)
            End Get
            Set
                Me("ApacheTbcExtHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ApacheTbcExtPort() As String
            Get
                Return CType(Me("ApacheTbcExtPort"),String)
            End Get
            Set
                Me("ApacheTbcExtPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ApacheWotlkExtHost() As String
            Get
                Return CType(Me("ApacheWotlkExtHost"),String)
            End Get
            Set
                Me("ApacheWotlkExtHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ApacheWotlkExtPort() As String
            Get
                Return CType(Me("ApacheWotlkExtPort"),String)
            End Get
            Set
                Me("ApacheWotlkExtPort") = value
            End Set
        End Property
        
        '''<summary>
        '''Тема для консоли
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Тема для консоли"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black Theme"),  _
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
        Public Property ConsoleTheme() As String
            Get
                Return CType(Me("ConsoleTheme"),String)
            End Get
            Set
                Me("ConsoleTheme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9"),  _
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
        Public Property ConsoleFontSize() As Single
            Get
                Return CType(Me("ConsoleFontSize"),Single)
            End Get
            Set
                Me("ConsoleFontSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DarkCyan"),  _
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
        Public Property RealmdConsoleForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("RealmdConsoleForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("RealmdConsoleForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SteelBlue"),  _
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
        Public Property WorldConsoleForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("WorldConsoleForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("WorldConsoleForeColor") = value
            End Set
        End Property
        
        '''<summary>
        '''Полный путь к запущенному серверу realmd
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Полный путь к запущенному серверу realmd"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CurrentFileRealmd() As String
            Get
                Return CType(Me("CurrentFileRealmd"),String)
            End Get
            Set
                Me("CurrentFileRealmd") = value
            End Set
        End Property
        
        '''<summary>
        '''Полный путь к запущенному серверу world
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Полный путь к запущенному серверу world"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CurrentFileWorld() As String
            Get
                Return CType(Me("CurrentFileWorld"),String)
            End Get
            Set
                Me("CurrentFileWorld") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CurrentServerSettings() As String
            Get
                Return CType(Me("CurrentServerSettings"),String)
            End Get
            Set
                Me("CurrentServerSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Regular")>  _
        Public Property ConsoleFontStyle() As Global.System.Drawing.FontStyle
            Get
                Return CType(Me("ConsoleFontStyle"),Global.System.Drawing.FontStyle)
            End Get
            Set
                Me("ConsoleFontStyle") = value
            End Set
        End Property
        
        '''<summary>
        '''Размер окна приложения при открытии
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Размер окна приложения при открытии"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("640, 420")>  _
        Public Property AppSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("AppSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("AppSize") = value
            End Set
        End Property
        
        '''<summary>
        '''Расположение окна при открытии
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Расположение окна при открытии"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80, 80")>  _
        Public Property AppLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("AppLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("AppLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LogLevel() As Integer
            Get
                Return CType(Me("LogLevel"),Integer)
            End Get
            Set
                Me("LogLevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SqlLogLevel() As Integer
            Get
                Return CType(Me("SqlLogLevel"),Integer)
            End Get
            Set
                Me("SqlLogLevel") = value
            End Set
        End Property
        
        '''<summary>
        '''Не выводить в консоль сообщения об ошибках.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Не выводить в консоль сообщения об ошибках."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property ConsoleMessageFilter() As Integer
            Get
                Return CType(Me("ConsoleMessageFilter"),Integer)
            End Get
            Set
                Me("ConsoleMessageFilter") = value
            End Set
        End Property
        
        '''<summary>
        '''Сохранять введённые команды в буфере.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Сохранять введённые команды в буфере."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseConsoleBuffer() As Boolean
            Get
                Return CType(Me("UseConsoleBuffer"),Boolean)
            End Get
            Set
                Me("UseConsoleBuffer") = value
            End Set
        End Property
        
        '''<summary>
        '''Автоподсказки в командной строке консоли.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Автоподсказки в командной строке консоли."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseCommandAutoHints() As Boolean
            Get
                Return CType(Me("UseCommandAutoHints"),Boolean)
            End Get
            Set
                Me("UseCommandAutoHints") = value
            End Set
        End Property
        
        '''<summary>
        '''Флаг обновления оформления консолей на ходу.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Флаг обновления оформления консолей на ходу."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UpdateConsoleRightNow() As Boolean
            Get
                Return CType(Me("UpdateConsoleRightNow"),Boolean)
            End Get
            Set
                Me("UpdateConsoleRightNow") = value
            End Set
        End Property
        
        '''<summary>
        '''Включить автоматический бэкап баз данных.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Включить автоматический бэкап баз данных."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseAutoBackupDatabase() As Boolean
            Get
                Return CType(Me("UseAutoBackupDatabase"),Boolean)
            End Get
            Set
                Me("UseAutoBackupDatabase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstStart() As Boolean
            Get
                Return CType(Me("FirstStart"),Boolean)
            End Get
            Set
                Me("FirstStart") = value
            End Set
        End Property
        
        '''<summary>
        '''Использовать в качестве резерных копий каталог проекта
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Использовать в качестве резерных копий каталог проекта"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseSqlBackupProjectFolder() As Boolean
            Get
                Return CType(Me("UseSqlBackupProjectFolder"),Boolean)
            End Get
            Set
                Me("UseSqlBackupProjectFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property AutosaveBackupCount() As Integer
            Get
                Return CType(Me("AutosaveBackupCount"),Integer)
            End Get
            Set
                Me("AutosaveBackupCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ManualBackupCount() As Integer
            Get
                Return CType(Me("ManualBackupCount"),Integer)
            End Get
            Set
                Me("ManualBackupCount") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.DevCake.WoW.SPP2Launcher.My.MySettings
            Get
                Return Global.DevCake.WoW.SPP2Launcher.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
